[workspace]
members = [
    "common",
    "parser",
    "programs/pump/pumpfun",
    "programs/pump/pumpswap",
    "tools/visual_inspector",
    "util/block_loader",
    "util/transaction_loader",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT"
repository = ""

[workspace.dependencies]
bs58 = "0.5.1"
common = { path = "common" }
dotenvy = "0.15.7"
pumpfun = { path = "programs/pump/pumpfun" }
pumpswap = { path = "programs/pump/pumpswap" }
serde_json = "1.0"
